name: Arduino-Pico Release Publisher

on:
  release:
    types: [published]

jobs:
  package:
    name: Update master JSON file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Deploy updated JSON
      env:
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
        BUILD_TYPE: package
        CI_GITHUB_API_KEY: ${{ secrets.GITHUB_TOKEN }}
      run: |
           tag=$(git describe --exact-match --tags)
           curl -L -o ./package_rp2040_index.json "https://github.com/earlephilhower/arduino-pico/releases/download/${tag}/package_rp2040_index.json"
           ./package/update_release.py --token ${CI_GITHUB_API_KEY} --repo earlephilhower/arduino-pico --tag global ./package_rp2040_index.json
